version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8181:8080"  # Exposes Jenkins on port 8080 of the host
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home  # Preserves Jenkins data between container restarts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Disables the setup wizard
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"  # Exposes PostgreSQL on port 5432 of the host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Preserves database between container restarts
    restart: unless-stopped

volumes:
  jenkins_home:
  postgres_data:
